#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 2.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master
    - staging
    - canary
    - v1.0
    - v2.0

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  NODE_UNICODETABLE_UNICODEDATA_TXT: '%appveyor_build_folder%\tools\UnicodeData.txt'
  nodejs_version: "7"
  azure_storage_access_key_staging:
    secure: LPX3Gv4dUzZ187kD3CZMsRWR1qNB9UM287fR1vh6FD4zAtUTzbPc5Hrh4syNokgYVPEN7JHxN0NL8Vt13DeCvW4STUyyFK+VgdDt5nTseMRsNbVST6ZYqmN19mF15yzi
  azure_storage_access_key:
    secure: pLJQvFOvO9DWeIX7KGdhUOSyEL7IH8CPegPlFMeZNod2fCeQIZ679KR8deYzrGeWKOAPi8j1+P0m4RSuorWnvXrU2MrJaxer912WbQHZ4Z/D8Q4kGFFwU3siJS9OzOap
  azure_storage_access_key_canary:
    secure: qvb26x/k1hCCVODmVKvc3c+3JHg1WX3VSmoI2KGLD6QE9WF+eSV4+4H71Qv9ORfz388G6B2VxM1JxHKRshwCZ59kbdRicpYE2ClEwGFxvROxlrzuGob9Bh0BvBHUDWPV
  keycdn_api_key:
    secure: HIuW8miNWA5qAAW3BGGQTMoxFlnWsoc4c9b4Yy1Eo9MYnHFNTjtV9BFdsm8pfLxj
  keycdn_prod:
    secure: J4aOP8rLKXjQ8hUVl0suBg==
  keycdn_staging:
    secure: 93E/Z5lVFdeq8uw87xvuZg==
  keycdn_canary:
    secure: mTyxClT8rVXIAfmz+DnIdQ==

# scripts that are called at very beginning, before repo cloning
init:
  - npm install gulp -g
  - git config --global core.autocrlf input

# scripts that run after cloning repository
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - ps: $splitted = $env:APPVEYOR_BUILD_VERSION.Split(".")
  - ps: $version = $splitted[0] + "." + $splitted[1]
  - ps: $decimalVersion = [decimal]$version
  - ps: $fistversion = [decimal]1.0
  - ps: >-
      if ($decimalVersion -le $fistversion)
      {
        $version = ""
      }
  - ps: gulp deploy --version $version

after_build:
  - cd dist\themes
  - 7z a %APPVEYOR_BUILD_FOLDER%\themes.zip "**\*.*" -r -x!".gitkeep" -x!".gitignore" -x!"*.map"

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  # pushing a single file
  - path: themes.zip
    name: themes
    type: zip

deploy:

# Production
  - provider: AzureBlob
    storage_account_name: snipcartpublic
    storage_access_key:
      secure: pLJQvFOvO9DWeIX7KGdhUOSyEL7IH8CPegPlFMeZNod2fCeQIZ679KR8deYzrGeWKOAPi8j1+P0m4RSuorWnvXrU2MrJaxer912WbQHZ4Z/D8Q4kGFFwU3siJS9OzOap
    container: themes
    artifact: themes
    set_content_type: true
    unzip: true
    on:
      branch:
        - master
        - v1.0
        - v2.0

  # Staging
  - provider: AzureBlob
    storage_account_name: snipcartcdndev
    storage_access_key:
      secure: LPX3Gv4dUzZ187kD3CZMsRWR1qNB9UM287fR1vh6FD4zAtUTzbPc5Hrh4syNokgYVPEN7JHxN0NL8Vt13DeCvW4STUyyFK+VgdDt5nTseMRsNbVST6ZYqmN19mF15yzi
    container: themes
    artifact: themes
    set_content_type: true
    unzip: true
    on:
      branch: staging

  # Canary
  - provider: AzureBlob
    storage_account_name: snipcartcdncanary
    storage_access_key:
      secure: qvb26x/k1hCCVODmVKvc3c+3JHg1WX3VSmoI2KGLD6QE9WF+eSV4+4H71Qv9ORfz388G6B2VxM1JxHKRshwCZ59kbdRicpYE2ClEwGFxvROxlrzuGob9Bh0BvBHUDWPV
    container: themes
    artifact: themes
    set_content_type: true
    unzip: true
    on:
      branch: canary

after_deploy:
  - ps: >-
      $auth = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $env:keycdn_api_key,"")))

      if (($env:APPVEYOR_REPO_BRANCH -eq "production"))
      {
        $url = "https://api.keycdn.com/zones/purge/{0}.json" -f $env:keycdn_prod
        Add-AppveyorMessage "Purging PRODUCTION CDN"
        Invoke-RestMethod -Headers @{Authorization=("Basic {0}" -f $auth)} -Uri $url
      }

      if (($env:APPVEYOR_REPO_BRANCH -eq "master"))
      {
        $url = "https://api.keycdn.com/zones/purge/{0}.json" -f $env:keycdn_prod
        Add-AppveyorMessage "Purging PRODUCTION CDN"
        Invoke-RestMethod -Headers @{Authorization=("Basic {0}" -f $auth)} -Uri $url
      }

      if (($env:APPVEYOR_REPO_BRANCH -eq "v2.0"))
      {
        $url = "https://api.keycdn.com/zones/purge/{0}.json" -f $env:keycdn_prod
        Add-AppveyorMessage "Purging PRODUCTION CDN"
        Invoke-RestMethod -Headers @{Authorization=("Basic {0}" -f $auth)} -Uri $url
      }

      if (($env:APPVEYOR_REPO_BRANCH -eq "staging"))
      {
        $url = "https://api.keycdn.com/zones/purge/{0}.json" -f $env:keycdn_staging
        Add-AppveyorMessage "Purging STAGING CDN"
        Invoke-RestMethod -Headers @{Authorization=("Basic {0}" -f $auth)} -Uri $url
      }

      if (($env:APPVEYOR_REPO_BRANCH -eq "canary"))
      {
        $url = "https://api.keycdn.com/zones/purge/{0}.json" -f $env:keycdn_canary
        Add-AppveyorMessage "Purging STAGING CDN"
        Invoke-RestMethod -Headers @{Authorization=("Basic {0}" -f $auth)} -Uri $url
      }
